{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE OverloadedStrings #-}
module Main where

import Chat (server, ServerState (..))
import Control.Applicative

import qualified Network.EngineIO.Snap as EIOSnap
import qualified Control.Concurrent.STM as STM
import qualified Snap.Core as Snap
import qualified Snap.Util.FileServe as Snap
import qualified Snap.Http.Server as Snap
import qualified Network.SocketIO as SocketIO

-- this module is autogenerated by cabal to specify path of your bin,lib generated by compling
import Paths_chat (getDataDir)

main :: IO ()
main = do
  state <- ServerState <$> STM.newTVarIO 0
  socketIoHandler <- SocketIO.initialize EIOSnap.snapAPI (server state)
  --dataDir <- getDataDir
  -- above is not valid ,so just specified the html path directly,as shown below
  let dataDir = "/home/kyle/Haskell/socketIOdemo/chat/resources/"
  Snap.quickHttpServe $
    Snap.route [ ("/socket.io", socketIoHandler)
               , ("/", Snap.serveDirectory dataDir)
               ]
